### ISSUE TITLE
https://github.com/linuxserver/docker-docker-compose is depreciated 

### ISSUE THREAD

**Issue by PackElend** [emmtte/LibreELEC-Raspberry#1]
Hi there,
may you want to update https://github.com/emmtte/LibreELEC-Startup#docker-docker-compose as https://github.com/linuxserver/docker-docker-compose is depreciated?

I posted the steps here https://forum.libreelec.tv/thread/13695-docker-compose-on-le/?postID=178346#post178346

**Comment by emmtte** [comment]
Thanks, updated
